# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1552, 1400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(230, 0, 1001, 821))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1250, 30, 291, 371))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.arrow_key_up_button = QtWidgets.QPushButton(self.groupBox_2)
        self.arrow_key_up_button.setEnabled(True)
        self.arrow_key_up_button.setGeometry(QtCore.QRect(110, 30, 90, 90))
        self.arrow_key_up_button.setStyleSheet("border: 0px;")
        self.arrow_key_up_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/arrowkey_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_up_button.setIcon(icon1)
        self.arrow_key_up_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_up_button.setCheckable(False)
        self.arrow_key_up_button.setChecked(False)
        self.arrow_key_up_button.setAutoRepeat(True)
        self.arrow_key_up_button.setObjectName("arrow_key_up_button")
        self.arrow_key_right_button = QtWidgets.QPushButton(self.groupBox_2)
        self.arrow_key_right_button.setEnabled(True)
        self.arrow_key_right_button.setGeometry(QtCore.QRect(190, 110, 90, 90))
        self.arrow_key_right_button.setStyleSheet("border: 0px;")
        self.arrow_key_right_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/arrowkey_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_right_button.setIcon(icon2)
        self.arrow_key_right_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_right_button.setCheckable(False)
        self.arrow_key_right_button.setChecked(False)
        self.arrow_key_right_button.setAutoRepeat(False)
        self.arrow_key_right_button.setObjectName("arrow_key_right_button")
        self.arrow_key_down_button = QtWidgets.QPushButton(self.groupBox_2)
        self.arrow_key_down_button.setEnabled(True)
        self.arrow_key_down_button.setGeometry(QtCore.QRect(110, 190, 90, 90))
        self.arrow_key_down_button.setStyleSheet("border: 0px;")
        self.arrow_key_down_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/arrowkey_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_down_button.setIcon(icon3)
        self.arrow_key_down_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_down_button.setCheckable(False)
        self.arrow_key_down_button.setChecked(False)
        self.arrow_key_down_button.setAutoRepeat(False)
        self.arrow_key_down_button.setObjectName("arrow_key_down_button")
        self.arrow_key_left_button = QtWidgets.QPushButton(self.groupBox_2)
        self.arrow_key_left_button.setEnabled(True)
        self.arrow_key_left_button.setGeometry(QtCore.QRect(30, 110, 90, 90))
        self.arrow_key_left_button.setStyleSheet("border: 0px;")
        self.arrow_key_left_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/arrowkey_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_left_button.setIcon(icon4)
        self.arrow_key_left_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_left_button.setCheckable(False)
        self.arrow_key_left_button.setChecked(False)
        self.arrow_key_left_button.setAutoRepeat(False)
        self.arrow_key_left_button.setObjectName("arrow_key_left_button")
        self.linearSpeed_slider = QtWidgets.QSlider(self.groupBox_2)
        self.linearSpeed_slider.setGeometry(QtCore.QRect(110, 290, 161, 31))
        self.linearSpeed_slider.setMaximum(10)
        self.linearSpeed_slider.setSingleStep(1)
        self.linearSpeed_slider.setPageStep(1)
        self.linearSpeed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.linearSpeed_slider.setObjectName("linearSpeed_slider")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 290, 81, 31))
        self.label.setObjectName("label")
        self.linearSpeed_label = QtWidgets.QLabel(self.groupBox_2)
        self.linearSpeed_label.setGeometry(QtCore.QRect(160, 270, 81, 31))
        self.linearSpeed_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.linearSpeed_label.setTextFormat(QtCore.Qt.AutoText)
        self.linearSpeed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.linearSpeed_label.setObjectName("linearSpeed_label")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 330, 81, 31))
        self.label_6.setObjectName("label_6")
        self.rotationSpeed_label = QtWidgets.QLabel(self.groupBox_2)
        self.rotationSpeed_label.setGeometry(QtCore.QRect(160, 310, 81, 31))
        self.rotationSpeed_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rotationSpeed_label.setTextFormat(QtCore.Qt.AutoText)
        self.rotationSpeed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotationSpeed_label.setObjectName("rotationSpeed_label")
        self.rotationSpeed_slider = QtWidgets.QSlider(self.groupBox_2)
        self.rotationSpeed_slider.setGeometry(QtCore.QRect(110, 330, 161, 31))
        self.rotationSpeed_slider.setMaximum(10)
        self.rotationSpeed_slider.setSingleStep(1)
        self.rotationSpeed_slider.setPageStep(1)
        self.rotationSpeed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rotationSpeed_slider.setObjectName("rotationSpeed_slider")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 201, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.realsense_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.realsense_status_label.setGeometry(QtCore.QRect(10, 40, 151, 31))
        self.realsense_status_label.setStyleSheet("color:red")
        self.realsense_status_label.setObjectName("realsense_status_label")
        self.yolo_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.yolo_status_label.setGeometry(QtCore.QRect(10, 80, 151, 31))
        self.yolo_status_label.setStyleSheet("color:red")
        self.yolo_status_label.setObjectName("yolo_status_label")
        self.detect_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.detect_status_label.setGeometry(QtCore.QRect(10, 120, 151, 31))
        self.detect_status_label.setStyleSheet("color:red")
        self.detect_status_label.setObjectName("detect_status_label")
        self.velodyne_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.velodyne_status_label.setGeometry(QtCore.QRect(10, 160, 151, 31))
        self.velodyne_status_label.setStyleSheet("color:red")
        self.velodyne_status_label.setObjectName("velodyne_status_label")
        self.rtab_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.rtab_status_label.setGeometry(QtCore.QRect(10, 200, 151, 31))
        self.rtab_status_label.setStyleSheet("color:red")
        self.rtab_status_label.setObjectName("rtab_status_label")
        self.arm_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.arm_status_label.setGeometry(QtCore.QRect(10, 240, 151, 31))
        self.arm_status_label.setStyleSheet("color:red")
        self.arm_status_label.setObjectName("arm_status_label")
        self.gripper_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.gripper_status_label.setGeometry(QtCore.QRect(10, 280, 151, 31))
        self.gripper_status_label.setStyleSheet("color:red")
        self.gripper_status_label.setObjectName("gripper_status_label")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(1250, 400, 291, 221))
        self.groupBox_4.setObjectName("groupBox_4")
        self.nav_start_button = QtWidgets.QPushButton(self.groupBox_4)
        self.nav_start_button.setGeometry(QtCore.QRect(40, 60, 181, 41))
        self.nav_start_button.setObjectName("nav_start_button")
        self.nav_stop_button = QtWidgets.QPushButton(self.groupBox_4)
        self.nav_stop_button.setGeometry(QtCore.QRect(40, 150, 181, 41))
        self.nav_stop_button.setObjectName("nav_stop_button")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 370, 201, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.yolo_onoff_button = QtWidgets.QPushButton(self.groupBox_5)
        self.yolo_onoff_button.setGeometry(QtCore.QRect(10, 120, 181, 41))
        self.yolo_onoff_button.setObjectName("yolo_onoff_button")
        self.yolo_pos_button = QtWidgets.QPushButton(self.groupBox_5)
        self.yolo_pos_button.setGeometry(QtCore.QRect(10, 40, 181, 41))
        self.yolo_pos_button.setObjectName("yolo_pos_button")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 850, 1221, 381))
        self.groupBox_7.setObjectName("groupBox_7")
        self.arm_x_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_x_LineEdit.setGeometry(QtCore.QRect(290, 60, 161, 31))
        self.arm_x_LineEdit.setReadOnly(True)
        self.arm_x_LineEdit.setObjectName("arm_x_LineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(230, 60, 31, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(230, 110, 31, 31))
        self.label_3.setObjectName("label_3")
        self.arm_y_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_y_LineEdit.setGeometry(QtCore.QRect(290, 110, 161, 31))
        self.arm_y_LineEdit.setReadOnly(True)
        self.arm_y_LineEdit.setObjectName("arm_y_LineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setGeometry(QtCore.QRect(230, 160, 31, 31))
        self.label_4.setObjectName("label_4")
        self.arm_z_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_z_LineEdit.setGeometry(QtCore.QRect(290, 160, 161, 31))
        self.arm_z_LineEdit.setReadOnly(True)
        self.arm_z_LineEdit.setObjectName("arm_z_LineEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setGeometry(QtCore.QRect(230, 210, 31, 31))
        self.label_5.setObjectName("label_5")
        self.arm_u_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_u_LineEdit.setGeometry(QtCore.QRect(290, 210, 161, 31))
        self.arm_u_LineEdit.setReadOnly(True)
        self.arm_u_LineEdit.setObjectName("arm_u_LineEdit")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(230, 260, 31, 31))
        self.label_7.setObjectName("label_7")
        self.arm_v_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_v_LineEdit.setGeometry(QtCore.QRect(290, 260, 161, 31))
        self.arm_v_LineEdit.setReadOnly(True)
        self.arm_v_LineEdit.setObjectName("arm_v_LineEdit")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setGeometry(QtCore.QRect(230, 310, 31, 31))
        self.label_8.setObjectName("label_8")
        self.arm_w_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_w_LineEdit.setGeometry(QtCore.QRect(290, 310, 161, 31))
        self.arm_w_LineEdit.setReadOnly(True)
        self.arm_w_LineEdit.setObjectName("arm_w_LineEdit")
        self.arm_init_button = QtWidgets.QPushButton(self.groupBox_7)
        self.arm_init_button.setGeometry(QtCore.QRect(780, 150, 181, 41))
        self.arm_init_button.setObjectName("arm_init_button")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(510, 310, 31, 31))
        self.label_9.setObjectName("label_9")
        self.arm_setY_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setY_LineEdit.setGeometry(QtCore.QRect(570, 110, 161, 31))
        self.arm_setY_LineEdit.setReadOnly(False)
        self.arm_setY_LineEdit.setObjectName("arm_setY_LineEdit")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(510, 60, 31, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(510, 110, 31, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(510, 260, 31, 31))
        self.label_12.setObjectName("label_12")
        self.arm_setZ_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setZ_LineEdit.setGeometry(QtCore.QRect(570, 160, 161, 31))
        self.arm_setZ_LineEdit.setReadOnly(False)
        self.arm_setZ_LineEdit.setObjectName("arm_setZ_LineEdit")
        self.arm_setU_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setU_LineEdit.setGeometry(QtCore.QRect(570, 210, 161, 31))
        self.arm_setU_LineEdit.setReadOnly(False)
        self.arm_setU_LineEdit.setObjectName("arm_setU_LineEdit")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(510, 210, 31, 31))
        self.label_13.setObjectName("label_13")
        self.arm_setW_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setW_LineEdit.setGeometry(QtCore.QRect(570, 310, 161, 31))
        self.arm_setW_LineEdit.setReadOnly(False)
        self.arm_setW_LineEdit.setObjectName("arm_setW_LineEdit")
        self.arm_setX_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setX_LineEdit.setGeometry(QtCore.QRect(570, 60, 161, 31))
        self.arm_setX_LineEdit.setReadOnly(False)
        self.arm_setX_LineEdit.setObjectName("arm_setX_LineEdit")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(510, 160, 31, 31))
        self.label_14.setObjectName("label_14")
        self.arm_setV_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setV_LineEdit.setGeometry(QtCore.QRect(570, 260, 161, 31))
        self.arm_setV_LineEdit.setReadOnly(False)
        self.arm_setV_LineEdit.setObjectName("arm_setV_LineEdit")
        self.arm_set_button = QtWidgets.QPushButton(self.groupBox_7)
        self.arm_set_button.setGeometry(QtCore.QRect(780, 220, 181, 41))
        self.arm_set_button.setObjectName("arm_set_button")
        self.arm_m_mode_button = QtWidgets.QRadioButton(self.groupBox_7)
        self.arm_m_mode_button.setGeometry(QtCore.QRect(780, 60, 181, 23))
        self.arm_m_mode_button.setChecked(True)
        self.arm_m_mode_button.setObjectName("arm_m_mode_button")
        self.arm_c_mode_button = QtWidgets.QRadioButton(self.groupBox_7)
        self.arm_c_mode_button.setGeometry(QtCore.QRect(780, 100, 181, 23))
        self.arm_c_mode_button.setChecked(False)
        self.arm_c_mode_button.setObjectName("arm_c_mode_button")
        self.arm_stop_button = QtWidgets.QPushButton(self.groupBox_7)
        self.arm_stop_button.setGeometry(QtCore.QRect(10, 70, 181, 41))
        self.arm_stop_button.setObjectName("arm_stop_button")
        self.arm_resume_button = QtWidgets.QPushButton(self.groupBox_7)
        self.arm_resume_button.setGeometry(QtCore.QRect(10, 140, 181, 41))
        self.arm_resume_button.setObjectName("arm_resume_button")
        self.arm_pause_button = QtWidgets.QPushButton(self.groupBox_7)
        self.arm_pause_button.setGeometry(QtCore.QRect(10, 220, 181, 41))
        self.arm_pause_button.setObjectName("arm_pause_button")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 580, 201, 231))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gripper_open_button = QtWidgets.QPushButton(self.groupBox_6)
        self.gripper_open_button.setGeometry(QtCore.QRect(10, 50, 181, 41))
        self.gripper_open_button.setObjectName("gripper_open_button")
        self.gripper_close_button = QtWidgets.QPushButton(self.groupBox_6)
        self.gripper_close_button.setGeometry(QtCore.QRect(10, 110, 181, 41))
        self.gripper_close_button.setObjectName("gripper_close_button")
        self.gripper_reset_button = QtWidgets.QPushButton(self.groupBox_6)
        self.gripper_reset_button.setGeometry(QtCore.QRect(10, 170, 181, 41))
        self.gripper_reset_button.setObjectName("gripper_reset_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1552, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AMR-Control"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Move"))
        self.label.setText(_translate("MainWindow", "Linear"))
        self.linearSpeed_label.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Rotation"))
        self.rotationSpeed_label.setText(_translate("MainWindow", "0"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Nodes status"))
        self.realsense_status_label.setText(_translate("MainWindow", "Realsense"))
        self.yolo_status_label.setText(_translate("MainWindow", "Yolo"))
        self.detect_status_label.setText(_translate("MainWindow", "Detect"))
        self.velodyne_status_label.setText(_translate("MainWindow", "Velodyne"))
        self.rtab_status_label.setText(_translate("MainWindow", "RTAB"))
        self.arm_status_label.setText(_translate("MainWindow", "TM_ARM"))
        self.gripper_status_label.setText(_translate("MainWindow", "Gripper"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Nav"))
        self.nav_start_button.setText(_translate("MainWindow", "Navigation"))
        self.nav_stop_button.setText(_translate("MainWindow", "Stop"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Yolo"))
        self.yolo_onoff_button.setText(_translate("MainWindow", "On/Off"))
        self.yolo_pos_button.setText(_translate("MainWindow", "Pos"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Arm"))
        self.arm_x_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.arm_y_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_4.setText(_translate("MainWindow", "Z"))
        self.arm_z_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_5.setText(_translate("MainWindow", "U"))
        self.arm_u_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_7.setText(_translate("MainWindow", "V"))
        self.arm_v_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_8.setText(_translate("MainWindow", "W"))
        self.arm_w_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.arm_init_button.setText(_translate("MainWindow", "Arm_init"))
        self.label_9.setText(_translate("MainWindow", "W"))
        self.arm_setY_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_10.setText(_translate("MainWindow", "X"))
        self.label_11.setText(_translate("MainWindow", "Y"))
        self.label_12.setText(_translate("MainWindow", "V"))
        self.arm_setZ_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.arm_setU_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_13.setText(_translate("MainWindow", "U"))
        self.arm_setW_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.arm_setX_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_14.setText(_translate("MainWindow", "Z"))
        self.arm_setV_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.arm_set_button.setText(_translate("MainWindow", "Set Arm"))
        self.arm_m_mode_button.setText(_translate("MainWindow", "Machine"))
        self.arm_c_mode_button.setText(_translate("MainWindow", "Comsumer"))
        self.arm_stop_button.setText(_translate("MainWindow", "Stop"))
        self.arm_resume_button.setText(_translate("MainWindow", "Resume"))
        self.arm_pause_button.setText(_translate("MainWindow", "Pause"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Gripper"))
        self.gripper_open_button.setText(_translate("MainWindow", "Open"))
        self.gripper_close_button.setText(_translate("MainWindow", "Close"))
        self.gripper_reset_button.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
