# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(783, 734)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 4, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.realsense_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.realsense_status_label.setStyleSheet("color:red")
        self.realsense_status_label.setObjectName("realsense_status_label")
        self.verticalLayout.addWidget(self.realsense_status_label)
        self.yolo_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.yolo_status_label.setStyleSheet("color:red")
        self.yolo_status_label.setObjectName("yolo_status_label")
        self.verticalLayout.addWidget(self.yolo_status_label)
        self.detect_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.detect_status_label.setStyleSheet("color:red")
        self.detect_status_label.setObjectName("detect_status_label")
        self.verticalLayout.addWidget(self.detect_status_label)
        self.velodyne_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.velodyne_status_label.setStyleSheet("color:red")
        self.velodyne_status_label.setObjectName("velodyne_status_label")
        self.verticalLayout.addWidget(self.velodyne_status_label)
        self.rtab_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.rtab_status_label.setStyleSheet("color:red")
        self.rtab_status_label.setObjectName("rtab_status_label")
        self.verticalLayout.addWidget(self.rtab_status_label)
        self.arm_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.arm_status_label.setStyleSheet("color:red")
        self.arm_status_label.setObjectName("arm_status_label")
        self.verticalLayout.addWidget(self.arm_status_label)
        self.gripper_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.gripper_status_label.setStyleSheet("color:red")
        self.gripper_status_label.setObjectName("gripper_status_label")
        self.verticalLayout.addWidget(self.gripper_status_label)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.nav_start_button = QtWidgets.QPushButton(self.groupBox_4)
        self.nav_start_button.setObjectName("nav_start_button")
        self.verticalLayout_4.addWidget(self.nav_start_button)
        self.nav_stop_button = QtWidgets.QPushButton(self.groupBox_4)
        self.nav_stop_button.setObjectName("nav_stop_button")
        self.verticalLayout_4.addWidget(self.nav_stop_button)
        self.gridLayout_3.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.yolo_pos_button = QtWidgets.QPushButton(self.groupBox_5)
        self.yolo_pos_button.setObjectName("yolo_pos_button")
        self.verticalLayout_2.addWidget(self.yolo_pos_button)
        self.yolo_onoff_button = QtWidgets.QPushButton(self.groupBox_5)
        self.yolo_onoff_button.setObjectName("yolo_onoff_button")
        self.verticalLayout_2.addWidget(self.yolo_onoff_button)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gripper_reset_button = QtWidgets.QPushButton(self.groupBox_6)
        self.gripper_reset_button.setObjectName("gripper_reset_button")
        self.verticalLayout_3.addWidget(self.gripper_reset_button)
        self.gripper_open_button = QtWidgets.QPushButton(self.groupBox_6)
        self.gripper_open_button.setObjectName("gripper_open_button")
        self.verticalLayout_3.addWidget(self.gripper_open_button)
        self.gripper_close_button = QtWidgets.QPushButton(self.groupBox_6)
        self.gripper_close_button.setObjectName("gripper_close_button")
        self.verticalLayout_3.addWidget(self.gripper_close_button)
        self.gridLayout_3.addWidget(self.groupBox_6, 4, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.arm_setZ_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setZ_LineEdit.setReadOnly(False)
        self.arm_setZ_LineEdit.setObjectName("arm_setZ_LineEdit")
        self.gridLayout_2.addWidget(self.arm_setZ_LineEdit, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.arm_set_button = QtWidgets.QPushButton(self.groupBox_7)
        self.arm_set_button.setObjectName("arm_set_button")
        self.gridLayout_2.addWidget(self.arm_set_button, 3, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 2, 1, 1)
        self.arm_v_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_v_LineEdit.setReadOnly(True)
        self.arm_v_LineEdit.setObjectName("arm_v_LineEdit")
        self.gridLayout_2.addWidget(self.arm_v_LineEdit, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.arm_stop_button = QtWidgets.QPushButton(self.groupBox_7)
        self.arm_stop_button.setObjectName("arm_stop_button")
        self.gridLayout_2.addWidget(self.arm_stop_button, 1, 4, 1, 1)
        self.arm_setW_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setW_LineEdit.setReadOnly(False)
        self.arm_setW_LineEdit.setObjectName("arm_setW_LineEdit")
        self.gridLayout_2.addWidget(self.arm_setW_LineEdit, 5, 3, 1, 1)
        self.arm_init_button = QtWidgets.QPushButton(self.groupBox_7)
        self.arm_init_button.setObjectName("arm_init_button")
        self.gridLayout_2.addWidget(self.arm_init_button, 2, 4, 1, 1)
        self.arm_w_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_w_LineEdit.setReadOnly(True)
        self.arm_w_LineEdit.setObjectName("arm_w_LineEdit")
        self.gridLayout_2.addWidget(self.arm_w_LineEdit, 5, 1, 1, 1)
        self.arm_z_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_z_LineEdit.setReadOnly(True)
        self.arm_z_LineEdit.setObjectName("arm_z_LineEdit")
        self.gridLayout_2.addWidget(self.arm_z_LineEdit, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.arm_x_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_x_LineEdit.setReadOnly(True)
        self.arm_x_LineEdit.setObjectName("arm_x_LineEdit")
        self.gridLayout_2.addWidget(self.arm_x_LineEdit, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.arm_setV_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setV_LineEdit.setReadOnly(False)
        self.arm_setV_LineEdit.setObjectName("arm_setV_LineEdit")
        self.gridLayout_2.addWidget(self.arm_setV_LineEdit, 4, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 2, 1, 1)
        self.arm_u_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_u_LineEdit.setReadOnly(True)
        self.arm_u_LineEdit.setObjectName("arm_u_LineEdit")
        self.gridLayout_2.addWidget(self.arm_u_LineEdit, 3, 1, 1, 1)
        self.arm_setX_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setX_LineEdit.setReadOnly(False)
        self.arm_setX_LineEdit.setObjectName("arm_setX_LineEdit")
        self.gridLayout_2.addWidget(self.arm_setX_LineEdit, 0, 3, 1, 1)
        self.arm_setU_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setU_LineEdit.setReadOnly(False)
        self.arm_setU_LineEdit.setObjectName("arm_setU_LineEdit")
        self.gridLayout_2.addWidget(self.arm_setU_LineEdit, 3, 3, 1, 1)
        self.arm_y_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_y_LineEdit.setReadOnly(True)
        self.arm_y_LineEdit.setObjectName("arm_y_LineEdit")
        self.gridLayout_2.addWidget(self.arm_y_LineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.arm_setY_LineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.arm_setY_LineEdit.setReadOnly(False)
        self.arm_setY_LineEdit.setObjectName("arm_setY_LineEdit")
        self.gridLayout_2.addWidget(self.arm_setY_LineEdit, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_7, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AMR-Control"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Nodes status"))
        self.realsense_status_label.setText(_translate("MainWindow", "Realsense"))
        self.yolo_status_label.setText(_translate("MainWindow", "Yolo"))
        self.detect_status_label.setText(_translate("MainWindow", "Detect"))
        self.velodyne_status_label.setText(_translate("MainWindow", "Velodyne"))
        self.rtab_status_label.setText(_translate("MainWindow", "RTAB"))
        self.arm_status_label.setText(_translate("MainWindow", "TM_ARM"))
        self.gripper_status_label.setText(_translate("MainWindow", "Gripper"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Nav"))
        self.nav_start_button.setText(_translate("MainWindow", "Navigation"))
        self.nav_stop_button.setText(_translate("MainWindow", "Stop"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Yolo"))
        self.yolo_pos_button.setText(_translate("MainWindow", "Pos"))
        self.yolo_onoff_button.setText(_translate("MainWindow", "On/Off"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Gripper"))
        self.gripper_reset_button.setText(_translate("MainWindow", "Reset"))
        self.gripper_open_button.setText(_translate("MainWindow", "Open"))
        self.gripper_close_button.setText(_translate("MainWindow", "Close"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Arm"))
        self.arm_setZ_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_4.setText(_translate("MainWindow", "Z"))
        self.arm_set_button.setText(_translate("MainWindow", "Set Arm"))
        self.label_14.setText(_translate("MainWindow", "Z"))
        self.arm_v_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_13.setText(_translate("MainWindow", "U"))
        self.label_11.setText(_translate("MainWindow", "Y"))
        self.label_8.setText(_translate("MainWindow", "W"))
        self.arm_stop_button.setText(_translate("MainWindow", "Stop"))
        self.arm_setW_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.arm_init_button.setText(_translate("MainWindow", "Arm_init"))
        self.arm_w_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.arm_z_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_5.setText(_translate("MainWindow", "U"))
        self.arm_x_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_7.setText(_translate("MainWindow", "V"))
        self.arm_setV_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_12.setText(_translate("MainWindow", "V"))
        self.arm_u_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.arm_setX_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.arm_setU_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.arm_y_LineEdit.setText(_translate("MainWindow", "0.0"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.label_9.setText(_translate("MainWindow", "W"))
        self.label_10.setText(_translate("MainWindow", "X"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.arm_setY_LineEdit.setText(_translate("MainWindow", "0.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
