# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(978, 766)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 290, 181, 261))
        self.groupBox.setObjectName("groupBox")
        self.aruco_on = QtWidgets.QPushButton(self.groupBox)
        self.aruco_on.setGeometry(QtCore.QRect(20, 50, 131, 61))
        self.aruco_on.setCheckable(True)
        self.aruco_on.setChecked(False)
        self.aruco_on.setAutoDefault(False)
        self.aruco_on.setDefault(False)
        self.aruco_on.setFlat(False)
        self.aruco_on.setObjectName("aruco_on")
        self.aruco_off = QtWidgets.QPushButton(self.groupBox)
        self.aruco_off.setGeometry(QtCore.QRect(20, 170, 131, 61))
        self.aruco_off.setObjectName("aruco_off")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(230, 0, 481, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(720, 0, 241, 351))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.arrow_key_up_button = QtWidgets.QPushButton(self.groupBox_2)
        self.arrow_key_up_button.setEnabled(True)
        self.arrow_key_up_button.setGeometry(QtCore.QRect(80, 30, 90, 90))
        self.arrow_key_up_button.setStyleSheet("border: 0px;")
        self.arrow_key_up_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/arrowkey_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_up_button.setIcon(icon1)
        self.arrow_key_up_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_up_button.setCheckable(False)
        self.arrow_key_up_button.setChecked(False)
        self.arrow_key_up_button.setAutoRepeat(False)
        self.arrow_key_up_button.setObjectName("arrow_key_up_button")
        self.arrow_key_right_button = QtWidgets.QPushButton(self.groupBox_2)
        self.arrow_key_right_button.setEnabled(True)
        self.arrow_key_right_button.setGeometry(QtCore.QRect(160, 110, 90, 90))
        self.arrow_key_right_button.setStyleSheet("border: 0px;")
        self.arrow_key_right_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/arrowkey_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_right_button.setIcon(icon2)
        self.arrow_key_right_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_right_button.setCheckable(False)
        self.arrow_key_right_button.setChecked(False)
        self.arrow_key_right_button.setAutoRepeat(False)
        self.arrow_key_right_button.setObjectName("arrow_key_right_button")
        self.arrow_key_down_button = QtWidgets.QPushButton(self.groupBox_2)
        self.arrow_key_down_button.setEnabled(True)
        self.arrow_key_down_button.setGeometry(QtCore.QRect(80, 190, 90, 90))
        self.arrow_key_down_button.setStyleSheet("border: 0px;")
        self.arrow_key_down_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/arrowkey_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_down_button.setIcon(icon3)
        self.arrow_key_down_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_down_button.setCheckable(False)
        self.arrow_key_down_button.setChecked(False)
        self.arrow_key_down_button.setAutoRepeat(False)
        self.arrow_key_down_button.setObjectName("arrow_key_down_button")
        self.arrow_key_left_button = QtWidgets.QPushButton(self.groupBox_2)
        self.arrow_key_left_button.setEnabled(True)
        self.arrow_key_left_button.setGeometry(QtCore.QRect(0, 110, 90, 90))
        self.arrow_key_left_button.setStyleSheet("border: 0px;")
        self.arrow_key_left_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/arrowkey_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_left_button.setIcon(icon4)
        self.arrow_key_left_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_left_button.setCheckable(False)
        self.arrow_key_left_button.setChecked(False)
        self.arrow_key_left_button.setAutoRepeat(False)
        self.arrow_key_left_button.setObjectName("arrow_key_left_button")
        self.speed_slider = QtWidgets.QSlider(self.groupBox_2)
        self.speed_slider.setGeometry(QtCore.QRect(110, 290, 121, 31))
        self.speed_slider.setMaximum(30)
        self.speed_slider.setSingleStep(5)
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setObjectName("speed_slider")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 290, 81, 31))
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 201, 251))
        self.groupBox_3.setObjectName("groupBox_3")
        self.realsense_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.realsense_status_label.setGeometry(QtCore.QRect(10, 40, 151, 31))
        self.realsense_status_label.setStyleSheet("color:red")
        self.realsense_status_label.setObjectName("realsense_status_label")
        self.aruco_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.aruco_status_label.setGeometry(QtCore.QRect(10, 80, 151, 31))
        self.aruco_status_label.setStyleSheet("color:red")
        self.aruco_status_label.setObjectName("aruco_status_label")
        self.muxaruco_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.muxaruco_status_label.setGeometry(QtCore.QRect(10, 120, 151, 31))
        self.muxaruco_status_label.setStyleSheet("color:red")
        self.muxaruco_status_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.muxaruco_status_label.setObjectName("muxaruco_status_label")
        self.yolo_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.yolo_status_label.setGeometry(QtCore.QRect(10, 160, 151, 31))
        self.yolo_status_label.setStyleSheet("color:red")
        self.yolo_status_label.setObjectName("yolo_status_label")
        self.detect_status_label = QtWidgets.QLabel(self.groupBox_3)
        self.detect_status_label.setGeometry(QtCore.QRect(10, 200, 151, 31))
        self.detect_status_label.setStyleSheet("color:red")
        self.detect_status_label.setObjectName("detect_status_label")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(720, 390, 241, 331))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 67, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 67, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 91, 31))
        self.label_4.setObjectName("label_4")
        self.nav_start_button = QtWidgets.QPushButton(self.groupBox_4)
        self.nav_start_button.setGeometry(QtCore.QRect(30, 270, 181, 41))
        self.nav_start_button.setObjectName("nav_start_button")
        self.nav_x_lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.nav_x_lineEdit.setGeometry(QtCore.QRect(100, 60, 121, 31))
        self.nav_x_lineEdit.setReadOnly(True)
        self.nav_x_lineEdit.setObjectName("nav_x_lineEdit")
        self.nav_y_lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.nav_y_lineEdit.setGeometry(QtCore.QRect(100, 130, 121, 31))
        self.nav_y_lineEdit.setReadOnly(True)
        self.nav_y_lineEdit.setObjectName("nav_y_lineEdit")
        self.nav_angle_lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.nav_angle_lineEdit.setEnabled(True)
        self.nav_angle_lineEdit.setGeometry(QtCore.QRect(100, 200, 121, 31))
        self.nav_angle_lineEdit.setReadOnly(True)
        self.nav_angle_lineEdit.setObjectName("nav_angle_lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AMR-Control"))
        self.groupBox.setTitle(_translate("MainWindow", "ArUCo_Image"))
        self.aruco_on.setText(_translate("MainWindow", "On"))
        self.aruco_off.setText(_translate("MainWindow", "Off"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Move"))
        self.label.setText(_translate("MainWindow", "Speed"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Nodes status"))
        self.realsense_status_label.setText(_translate("MainWindow", "Realsense"))
        self.aruco_status_label.setText(_translate("MainWindow", "ArUCo"))
        self.muxaruco_status_label.setText(_translate("MainWindow", "MuxArUCo"))
        self.yolo_status_label.setText(_translate("MainWindow", "Yolo"))
        self.detect_status_label.setText(_translate("MainWindow", "Detect"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Nav"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.label_4.setText(_translate("MainWindow", "Angle"))
        self.nav_start_button.setText(_translate("MainWindow", "Navigation"))
        self.nav_x_lineEdit.setText(_translate("MainWindow", "0"))
        self.nav_y_lineEdit.setText(_translate("MainWindow", "0"))
        self.nav_angle_lineEdit.setText(_translate("MainWindow", "1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
