# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/amm_control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Amm_control(object):
    def setupUi(self, Amm_control):
        Amm_control.setObjectName("Amm_control")
        Amm_control.resize(300, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Amm_control.sizePolicy().hasHeightForWidth())
        Amm_control.setSizePolicy(sizePolicy)
        Amm_control.setMinimumSize(QtCore.QSize(300, 410))
        Amm_control.setMaximumSize(QtCore.QSize(400, 550))
        self.gridLayout_3 = QtWidgets.QGridLayout(Amm_control)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(Amm_control)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.arrow_key_up_button = QtWidgets.QPushButton(self.widget)
        self.arrow_key_up_button.setEnabled(True)
        self.arrow_key_up_button.setStyleSheet("border: 0px;")
        self.arrow_key_up_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../icon/arrowkey_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_up_button.setIcon(icon)
        self.arrow_key_up_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_up_button.setCheckable(False)
        self.arrow_key_up_button.setChecked(False)
        self.arrow_key_up_button.setAutoRepeat(True)
        self.arrow_key_up_button.setObjectName("arrow_key_up_button")
        self.gridLayout.addWidget(self.arrow_key_up_button, 0, 1, 1, 1)
        self.arrow_key_left_button = QtWidgets.QPushButton(self.widget)
        self.arrow_key_left_button.setEnabled(True)
        self.arrow_key_left_button.setStyleSheet("border: 0px;")
        self.arrow_key_left_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/../icon/arrowkey_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_left_button.setIcon(icon1)
        self.arrow_key_left_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_left_button.setCheckable(False)
        self.arrow_key_left_button.setChecked(False)
        self.arrow_key_left_button.setAutoRepeat(False)
        self.arrow_key_left_button.setObjectName("arrow_key_left_button")
        self.gridLayout.addWidget(self.arrow_key_left_button, 1, 0, 1, 1)
        self.arrow_key_right_button = QtWidgets.QPushButton(self.widget)
        self.arrow_key_right_button.setEnabled(True)
        self.arrow_key_right_button.setStyleSheet("border: 0px;")
        self.arrow_key_right_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui/../icon/arrowkey_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_right_button.setIcon(icon2)
        self.arrow_key_right_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_right_button.setCheckable(False)
        self.arrow_key_right_button.setChecked(False)
        self.arrow_key_right_button.setAutoRepeat(False)
        self.arrow_key_right_button.setObjectName("arrow_key_right_button")
        self.gridLayout.addWidget(self.arrow_key_right_button, 1, 2, 1, 1)
        self.arrow_key_down_button = QtWidgets.QPushButton(self.widget)
        self.arrow_key_down_button.setEnabled(True)
        self.arrow_key_down_button.setStyleSheet("border: 0px;")
        self.arrow_key_down_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui/../icon/arrowkey_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arrow_key_down_button.setIcon(icon3)
        self.arrow_key_down_button.setIconSize(QtCore.QSize(80, 80))
        self.arrow_key_down_button.setCheckable(False)
        self.arrow_key_down_button.setChecked(False)
        self.arrow_key_down_button.setAutoRepeat(False)
        self.arrow_key_down_button.setObjectName("arrow_key_down_button")
        self.gridLayout.addWidget(self.arrow_key_down_button, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Amm_control)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rotationSpeed_slider = QtWidgets.QSlider(self.widget_2)
        self.rotationSpeed_slider.setMaximum(10)
        self.rotationSpeed_slider.setSingleStep(1)
        self.rotationSpeed_slider.setPageStep(1)
        self.rotationSpeed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rotationSpeed_slider.setObjectName("rotationSpeed_slider")
        self.gridLayout_2.addWidget(self.rotationSpeed_slider, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.linearSpeed_slider = QtWidgets.QSlider(self.widget_2)
        self.linearSpeed_slider.setMaximum(10)
        self.linearSpeed_slider.setSingleStep(1)
        self.linearSpeed_slider.setPageStep(1)
        self.linearSpeed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.linearSpeed_slider.setObjectName("linearSpeed_slider")
        self.gridLayout_2.addWidget(self.linearSpeed_slider, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.linearSpeed_label = QtWidgets.QLabel(self.widget_2)
        self.linearSpeed_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.linearSpeed_label.setTextFormat(QtCore.Qt.AutoText)
        self.linearSpeed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.linearSpeed_label.setObjectName("linearSpeed_label")
        self.gridLayout_2.addWidget(self.linearSpeed_label, 0, 2, 1, 1)
        self.rotationSpeed_label = QtWidgets.QLabel(self.widget_2)
        self.rotationSpeed_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rotationSpeed_label.setTextFormat(QtCore.Qt.AutoText)
        self.rotationSpeed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotationSpeed_label.setObjectName("rotationSpeed_label")
        self.gridLayout_2.addWidget(self.rotationSpeed_label, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 1, 0, 1, 1)

        self.retranslateUi(Amm_control)
        QtCore.QMetaObject.connectSlotsByName(Amm_control)

    def retranslateUi(self, Amm_control):
        _translate = QtCore.QCoreApplication.translate
        Amm_control.setWindowTitle(_translate("Amm_control", "Amm Control"))
        self.label.setText(_translate("Amm_control", "Linear"))
        self.label_6.setText(_translate("Amm_control", "Rotation"))
        self.linearSpeed_label.setText(_translate("Amm_control", "0"))
        self.rotationSpeed_label.setText(_translate("Amm_control", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Amm_control = QtWidgets.QWidget()
    ui = Ui_Amm_control()
    ui.setupUi(Amm_control)
    Amm_control.show()
    sys.exit(app.exec_())
